# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EAJA Hours 3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EAJA Hours 3

	pod 'RealmSwift'

end
